repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: mixed-line-ending
  - repo: local
    hooks:
      - id: verify-versions-sync
        name: verify-versions-sync
        entry: npx tsx scripts/verify-versions-sync.mts
        language: system
        pass_filenames: false
        always_run: true
      - id: verify-version-bump
        name: verify-version-bump
        entry: npx tsx scripts/verify-version-bump.mts
        language: system
        pass_filenames: false
        always_run: true
      - id: biome
        name: biome
        entry: npx biome check --write --staged --no-errors-on-unmatched
        language: system
        pass_filenames: false
